### ISSUE TITLE
filesys.ado throwing java exception

### ISSUE THREAD

**Issue by wbuchanan** [wbuchanan/brewscheme#34]
Based on comment https://github.com/wbuchanan/brewscheme/issues/21#issuecomment-173261527 

User reported:

```
. filesys `c(sysdir_personal)'b, attr dis 
java.lang.UnsupportedOperationException
at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:192)
at java.nio.file.Files.readAttributes(Files.java:1737)
at org.paces.Stata.FileCreated.setPosixAttributes(FileCreated.java:178)
at org.paces.Stata.FileCreated.(FileCreated.java:121)
at org.paces.Stata.StataFileSystem.fileCreated(StataFileSystem.java:24)
```

**Comment by wbuchanan** [comment]
Fixed error in filesys.ado that caused the program to set the OS string to POSIX on Windoze systems.
